/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeamDeliveryRouteImport } from './routes/beam-delivery'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as CaramelizeRouteImport } from './routes/caramelize'
import { Route as CheckDishRouteImport } from './routes/check-dish'
import { Route as ChopRouteImport } from './routes/chop'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as CookingRouteImport } from './routes/cooking'
import { Route as FilteringRouteImport } from './routes/filtering'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as KitchenHubRouteImport } from './routes/kitchen-hub'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MarinateRouteImport } from './routes/marinate'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MixingRouteImport } from './routes/mixing'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as RecipeBookRouteImport } from './routes/recipe-book'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemDeliveryRouteImport } from './routes/system-delivery'
import { Route as TransformRouteImport } from './routes/transform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeamDeliveryRoute = BeamDeliveryRouteImport.update({
  id: '/beam-delivery',
  path: '/beam-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const CaramelizeRoute = CaramelizeRouteImport.update({
  id: '/caramelize',
  path: '/caramelize',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckDishRoute = CheckDishRouteImport.update({
  id: '/check-dish',
  path: '/check-dish',
  getParentRoute: () => rootRouteImport,
} as any)
const ChopRoute = ChopRouteImport.update({
  id: '/chop',
  path: '/chop',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingRoute = CookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => rootRouteImport,
} as any)
const FilteringRoute = FilteringRouteImport.update({
  id: '/filtering',
  path: '/filtering',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenHubRoute = KitchenHubRouteImport.update({
  id: '/kitchen-hub',
  path: '/kitchen-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarinateRoute = MarinateRouteImport.update({
  id: '/marinate',
  path: '/marinate',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MixingRoute = MixingRouteImport.update({
  id: '/mixing',
  path: '/mixing',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeBookRoute = RecipeBookRouteImport.update({
  id: '/recipe-book',
  path: '/recipe-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemDeliveryRoute = SystemDeliveryRouteImport.update({
  id: '/system-delivery',
  path: '/system-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const TransformRoute = TransformRouteImport.update({
  id: '/transform',
  path: '/transform',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beam-delivery': typeof BeamDeliveryRoute
  '/briefing': typeof BriefingRoute
  '/caramelize': typeof CaramelizeRoute
  '/check-dish': typeof CheckDishRoute
  '/chop': typeof ChopRoute
  '/complete': typeof CompleteRoute
  '/cooking': typeof CookingRoute
  '/filtering': typeof FilteringRoute
  '/generate': typeof GenerateRoute
  '/how-to-play': typeof HowToPlayRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-hub': typeof KitchenHubRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marinate': typeof MarinateRoute
  '/menu': typeof MenuRoute
  '/mixing': typeof MixingRoute
  '/pantry': typeof PantryRoute
  '/recipe-book': typeof RecipeBookRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/system-delivery': typeof SystemDeliveryRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beam-delivery': typeof BeamDeliveryRoute
  '/briefing': typeof BriefingRoute
  '/caramelize': typeof CaramelizeRoute
  '/check-dish': typeof CheckDishRoute
  '/chop': typeof ChopRoute
  '/complete': typeof CompleteRoute
  '/cooking': typeof CookingRoute
  '/filtering': typeof FilteringRoute
  '/generate': typeof GenerateRoute
  '/how-to-play': typeof HowToPlayRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-hub': typeof KitchenHubRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marinate': typeof MarinateRoute
  '/menu': typeof MenuRoute
  '/mixing': typeof MixingRoute
  '/pantry': typeof PantryRoute
  '/recipe-book': typeof RecipeBookRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/system-delivery': typeof SystemDeliveryRoute
  '/transform': typeof TransformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beam-delivery': typeof BeamDeliveryRoute
  '/briefing': typeof BriefingRoute
  '/caramelize': typeof CaramelizeRoute
  '/check-dish': typeof CheckDishRoute
  '/chop': typeof ChopRoute
  '/complete': typeof CompleteRoute
  '/cooking': typeof CookingRoute
  '/filtering': typeof FilteringRoute
  '/generate': typeof GenerateRoute
  '/how-to-play': typeof HowToPlayRoute
  '/kitchen': typeof KitchenRoute
  '/kitchen-hub': typeof KitchenHubRoute
  '/labs': typeof LabsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/marinate': typeof MarinateRoute
  '/menu': typeof MenuRoute
  '/mixing': typeof MixingRoute
  '/pantry': typeof PantryRoute
  '/recipe-book': typeof RecipeBookRoute
  '/score': typeof ScoreRoute
  '/settings': typeof SettingsRoute
  '/system-delivery': typeof SystemDeliveryRoute
  '/transform': typeof TransformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beam-delivery'
    | '/briefing'
    | '/caramelize'
    | '/check-dish'
    | '/chop'
    | '/complete'
    | '/cooking'
    | '/filtering'
    | '/generate'
    | '/how-to-play'
    | '/kitchen'
    | '/kitchen-hub'
    | '/labs'
    | '/leaderboard'
    | '/marinate'
    | '/menu'
    | '/mixing'
    | '/pantry'
    | '/recipe-book'
    | '/score'
    | '/settings'
    | '/system-delivery'
    | '/transform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beam-delivery'
    | '/briefing'
    | '/caramelize'
    | '/check-dish'
    | '/chop'
    | '/complete'
    | '/cooking'
    | '/filtering'
    | '/generate'
    | '/how-to-play'
    | '/kitchen'
    | '/kitchen-hub'
    | '/labs'
    | '/leaderboard'
    | '/marinate'
    | '/menu'
    | '/mixing'
    | '/pantry'
    | '/recipe-book'
    | '/score'
    | '/settings'
    | '/system-delivery'
    | '/transform'
  id:
    | '__root__'
    | '/'
    | '/beam-delivery'
    | '/briefing'
    | '/caramelize'
    | '/check-dish'
    | '/chop'
    | '/complete'
    | '/cooking'
    | '/filtering'
    | '/generate'
    | '/how-to-play'
    | '/kitchen'
    | '/kitchen-hub'
    | '/labs'
    | '/leaderboard'
    | '/marinate'
    | '/menu'
    | '/mixing'
    | '/pantry'
    | '/recipe-book'
    | '/score'
    | '/settings'
    | '/system-delivery'
    | '/transform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeamDeliveryRoute: typeof BeamDeliveryRoute
  BriefingRoute: typeof BriefingRoute
  CaramelizeRoute: typeof CaramelizeRoute
  CheckDishRoute: typeof CheckDishRoute
  ChopRoute: typeof ChopRoute
  CompleteRoute: typeof CompleteRoute
  CookingRoute: typeof CookingRoute
  FilteringRoute: typeof FilteringRoute
  GenerateRoute: typeof GenerateRoute
  HowToPlayRoute: typeof HowToPlayRoute
  KitchenRoute: typeof KitchenRoute
  KitchenHubRoute: typeof KitchenHubRoute
  LabsRoute: typeof LabsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MarinateRoute: typeof MarinateRoute
  MenuRoute: typeof MenuRoute
  MixingRoute: typeof MixingRoute
  PantryRoute: typeof PantryRoute
  RecipeBookRoute: typeof RecipeBookRoute
  ScoreRoute: typeof ScoreRoute
  SettingsRoute: typeof SettingsRoute
  SystemDeliveryRoute: typeof SystemDeliveryRoute
  TransformRoute: typeof TransformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beam-delivery': {
      id: '/beam-delivery'
      path: '/beam-delivery'
      fullPath: '/beam-delivery'
      preLoaderRoute: typeof BeamDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caramelize': {
      id: '/caramelize'
      path: '/caramelize'
      fullPath: '/caramelize'
      preLoaderRoute: typeof CaramelizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-dish': {
      id: '/check-dish'
      path: '/check-dish'
      fullPath: '/check-dish'
      preLoaderRoute: typeof CheckDishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chop': {
      id: '/chop'
      path: '/chop'
      fullPath: '/chop'
      preLoaderRoute: typeof ChopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking': {
      id: '/cooking'
      path: '/cooking'
      fullPath: '/cooking'
      preLoaderRoute: typeof CookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtering': {
      id: '/filtering'
      path: '/filtering'
      fullPath: '/filtering'
      preLoaderRoute: typeof FilteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-hub': {
      id: '/kitchen-hub'
      path: '/kitchen-hub'
      fullPath: '/kitchen-hub'
      preLoaderRoute: typeof KitchenHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marinate': {
      id: '/marinate'
      path: '/marinate'
      fullPath: '/marinate'
      preLoaderRoute: typeof MarinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixing': {
      id: '/mixing'
      path: '/mixing'
      fullPath: '/mixing'
      preLoaderRoute: typeof MixingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-book': {
      id: '/recipe-book'
      path: '/recipe-book'
      fullPath: '/recipe-book'
      preLoaderRoute: typeof RecipeBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-delivery': {
      id: '/system-delivery'
      path: '/system-delivery'
      fullPath: '/system-delivery'
      preLoaderRoute: typeof SystemDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transform': {
      id: '/transform'
      path: '/transform'
      fullPath: '/transform'
      preLoaderRoute: typeof TransformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeamDeliveryRoute: BeamDeliveryRoute,
  BriefingRoute: BriefingRoute,
  CaramelizeRoute: CaramelizeRoute,
  CheckDishRoute: CheckDishRoute,
  ChopRoute: ChopRoute,
  CompleteRoute: CompleteRoute,
  CookingRoute: CookingRoute,
  FilteringRoute: FilteringRoute,
  GenerateRoute: GenerateRoute,
  HowToPlayRoute: HowToPlayRoute,
  KitchenRoute: KitchenRoute,
  KitchenHubRoute: KitchenHubRoute,
  LabsRoute: LabsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MarinateRoute: MarinateRoute,
  MenuRoute: MenuRoute,
  MixingRoute: MixingRoute,
  PantryRoute: PantryRoute,
  RecipeBookRoute: RecipeBookRoute,
  ScoreRoute: ScoreRoute,
  SettingsRoute: SettingsRoute,
  SystemDeliveryRoute: SystemDeliveryRoute,
  TransformRoute: TransformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
